### PR TITLE
Updated code structure for mesh export - errors to fix

### PR DESCRIPTION
**Pull request by fullcontrol-xyz**
I've reworked the code to have a 3rd transform option of '3d_model' in addition to the existing options for 'gcode' and 'plot'

I've also begun to separate out the specific meshing aspects of `plot` into a separate function which can then be used when generating a plot and generating an stl file. This can be tidied up further in the future when we add more functionality to the '3d_model' transform option. However, there are currently issues with the 'plot' transform option. Most of the tutorial notebooks work fine, but a few have issues as described below. I'm not sure whether these are due to changes I made for this pr, or changes you made from the existing fullcontrol repo. Regardless, I think they're all to do with colour and are likely v easy for you to spot the cause of. I tried to pull the colour aspects out of my new `generate_mesh` function (to put them in `plot` instead - both in plotly.py), but ended up with more errors. Can you have a look at the errors I've detailed below and see if you can see an easy fix. In the future, we may want the '3d_model' output to have colour too, so it would be fine if the colour stuff is moved into its own small new function within plotly.py.

I've left the two error-causing tutorial notebooks in the top level for convenience. They can be deleted from there (but remain in docs) after debugging. 

There is also a new tutorial notebook, briefly showing the stl export functionality. This seems to work fine.

Two code cells cause an error.

In state_objects.ipynb, the following code-cell has an error:

```
steps = []
steps.append(fc.Point(x=0, y=0, z=0, color=[0,0,1]))
steps.append(fc.Point(x=25, y=5))
steps.append(fc.Point(x=0,y=10))
steps.append(fc.Point(y=30, color=[0,1,1])) # line plotted with a gradient transition to this color
steps.append(fc.Point(x=25, y=40))
steps.append(fc.Point(x=0, y=50))
steps.append(fc.Point(color=[0,0,1])) # line plotted with an instant color change
steps.append(fc.Point(y=60))
fc.transform(steps, 'plot', fc.PlotControls(color_type='manual'))
```

In lab_geometry.ipynb, the following code cell causes an error:
```
points = [fc.Point(x=10, y=10, z=0.2), fc.Point(x=15, y=15, z=0.2), fc.Point(x=20, y=10, z=0.2), fc.Point(x=10, y=10, z=0.2)]
offset = 0.4
steps = fclab.offset_path(points, offset, repeats=10, travel = True, include_original=True, arc_outer_corners=True, arc_segments=16)
steps.append(fc.PlotAnnotation(label="add radii to corners with 'arc_outer_corners' and 'arc_segments' parameters"))
fc.transform(steps, 'plot', fc.PlotControls(color_type='print_sequence', tube_type='flow'))
```

Additionally, the colours are incorrect in the four plots in the 'convex (streamline slicing)' section.

### CODE REVIEW

**Comment by ES-Alexander** [comment]
Just noting here that I have seen this and been meaning to get to it, but have been struggling to make time to review it. 

Hopefully I can do so this weekend :-)

**Comment by fullcontrol-xyz** [comment]
Excellent! I've been meaning to comment on here to check you saw it. It's gonna be good 👍

**Comment by ES-Alexander** [comment]
I did most of the integration of this tonight (with a few minor changes/improvements), but I haven't yet resolved the bug you ran into (although I have fixed a different bug, that your reported one incidentally brought to light).

I checked from before your changes and the bug is not present, so it has indeed been introduced through the changes in this PR. It seems when colours are specified for all the points (for plotting) it's somehow ending up with an extra colour, which is then causing an array size mismatch between the colours and the points. I haven't yet had a chance to look for the cause of the bug.

I was hoping to finish this off tonight, and I don't expect it'll be overly difficult to track down, but it's now 3am and I need some sleep, so it'll have to wait for later this week. I'm happy to have finally gotten back to this, and now that my head's back in the project there's less of a barrier to me returning to finish it off :-)

**Comment by fullcontrol-xyz** [comment]
Ah brilliant!

That makes sense with the new bug. It's probably due to me moving some of the code into a separate function (with the intention of splitting things into modules with standalone value in the future). I think the arrays are different lengths depending on whether the user choose the `cylinder` or `flow` options. So perhaps I inadvertently added a problem to do with that. But I'm not sure why it only happens for a very few of the tutorial situations. Thanks for getting back to it! I've been completely swamped recently with exam marking anyway, so it's quite good timing, as those extra things are beginning to ease off now. Looking forward to getting this out there!

**Comment by ES-Alexander** [comment]
The bug did end up being pretty straightforward:
1. `colors_now` was being (conditionally*) overwritten in the original `plot` function, but 
2. when that got refactored into the `generate_mesh` function it was only changing it within that function scope, so
3. I changed it to modify the input list instead of assigning the variable name to a new value

*the conditional is why it was only happening for some examples.

I've now merged in these changes, but since I made some adjustments to them I added them independently of this PR and just set you as the author of the commits.

I'm closing this PR now, since the changes are already part of the branch :-)

**Pull request closed without merging**
